# Generated by Django 4.2.6 on 2023-11-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='signature',
            field=models.CharField(default='Thulane Ximba | ximba.thulane01@gmail.com', max_length=140),
        ),
    ]
